### ISSUE TITLE
Inconsistent formatting (tabs & spaces)

### ISSUE THREAD

**Issue by ordinathorreur** [tomharvey/pwinty3-rb#11]
It might be good to move the codebase to use 2 spaces throughout. Some files use tabs and others use spaces, some have a mixture of both.

**Comment by tomharvey** [comment]
As loath as I am to use rubocop, it's a fair request that whitespace is standard. And, given the crappy diff created when doing this we might as well get it over with sooner than later.

https://github.com/tomharvey/pwinty3-rb/pull/13

**Comment by tomharvey** [comment]
I'll merge that PR at the end of the week in case you've got some feedback on it @ordinathorreur 

LMK if you want it merged before you rewrite the tests to handle the order IDs 👍 

Thanks
