### ISSUE TITLE
Order.update fails with error "NoMethodError (undefined method `packingSlipUrl=' for #<Pwinty::Order:..>)"

### ISSUE THREAD

**Issue by martron** [tomharvey/pwinty3-rb#14]
When I try to update an order that's already been created in Pwinty I receive the following error:

`NoMethodError (undefined method `packingSlipUrl=' for #<Pwinty::Order:0x000055653f662ea8>)`

I've just started playing around with this gem so forgive my inexperience but it seems like the ['attribute?' call in order.rb](https://github.com/tomharvey/pwinty3-rb/blob/master/lib/pwinty/order.rb#L20) doesn't create a setter for packingSlipUrl

Could this be an incompatibility in the dry-struct library I've got installed?  

    $ gem list | grep dry
    dry-configurable (0.11.5)
    dry-container (0.7.2)
    dry-core (0.4.9)
    dry-equalizer (0.3.0)
    dry-inflector (0.2.0)
    dry-logic (1.0.6)
    dry-struct (1.3.0)
    dry-struct-setters (0.2.0)
    dry-types (1.4.0)

    $ gem list | grep pwinty
    pwinty (3.0.5)

If so, then the dependency in this gem's Gemfile might need to be updated.

Thanks

**Comment by tomharvey** [comment]
Hey - thanks for flagging. I'll look into this some more tomorrow.

Doe stoa order you're trying to update have a packing slip before you attempt the update, and are you updating that attribute?

I'm using dry-struct 1.3.0 as well, and I think the optional keys feature came in with v1.0 https://dry-rb.org/gems/dry-types/1.0/hash-schemas/#optional-keys

**Comment by martron** [comment]
> Doe stoa order you're trying to update have a packing slip before you attempt the update, and are you updating that attribute?

No it doesn't.  However, the object has a .packingSlipUrl?= method which makes me think that it's the [dry-struct-setters gem that doesn't quite know what to do with omit-able attributes](https://github.com/tbuehlmann/dry-struct-setters/blob/master/lib/dry/struct/setters.rb).

**Comment by martron** [comment]
I guess that makes sense considering the dry-struct-setters gem hasn't had an update since before dry-struct 1.0 was release.

**Comment by tomharvey** [comment]
I've raised this in the dry-struct-setters project and will try to get it fixed there. https://github.com/tbuehlmann/dry-struct-setters/issues/2

**Comment by tomharvey** [comment]
In the meantime - in the name of working pragmatic code - I've added a quick fix to allow for the updating of packingSlipUrl https://github.com/tomharvey/pwinty3-rb/releases/tag/v3.0.6

It's on rubygems as v3.0.6 so make sure your Gemfile is requesting that version, or newer, and you should not see the error any more.

I'll close this for now. Reopen it if you're still seeing an error. And, I'll track a fix to the dry-struct-setters project in the issue I raised on that repo.

Thanks again for flagging the problem. Hope this works now.

**Comment by tomharvey** [comment]
@martron dry-struct-setters has been updated to v0.3.0 to work with omitable attributes now.

At some point I’ll update the dependencies here to use that version and unravel the fix I hacked in here.

**Comment by martron** [comment]
@tomharvey no problem, thanks for tackling it down through the chain.
