### ISSUE TITLE
Any 404 status code raises potentially misleading Pwinty::OrderNotFound error

### ISSUE THREAD

**Issue by ordinathorreur** [tomharvey/pwinty3-rb#7]
Any request resulting in a 404 response status code raises a `Pwinty::OrderNotFound` error in the Faraday Middleware [here](https://github.com/tomharvey/pwinty3-rb/blob/bbf8eae1befa0f879fc48c9b8419ebf0b6d582c6/lib/pwinty/http_errors.rb#L8) which I found to be rather misleading, perhaps the error class should be named something more generic `Pwinty::NotFound`

**Comment by tomharvey** [comment]
Fair enough, it's more in line with their API docs for this to be a generic 'not found' as opposed to an order not found.

Out of curiosity - what was the 404 you were getting if not an order

**Comment by tomharvey** [comment]
https://github.com/tomharvey/pwinty3-rb/pull/12

**Comment by ordinathorreur** [comment]
I think it was when I was trying to create my first order. It was confusing me because the error made me think the order had been created successfully, but was subsequently not being found, when in fact it had never been created in the first place.
