### ISSUE TITLE
Specs depend on specific order ids

### ISSUE THREAD

**Issue by ordinathorreur** [tomharvey/pwinty3-rb#8]
I was just trying to write a new spec and found I couldn't just delete the VCR cassettes directory and get the other specs to pass which was a bit unexpected. I'm getting lots of 'You are not authorised to view this order' api errors.

I don't personally commit VCR cassettes to my projects, but I can see why some people might want to, especially if there are a lot of dependencies etc. However, this library doesn't seem to fall into that category, but it does make adding new specs and running the full test suite a little difficult if specs depend on orders existing that other developers can't access.

Perhaps these tests could be become less brittle by creating an order in a test setup instead? That way anyone with the correct dependencies can run the full suite. This also means that this library can more easily be adapted to future Pwinty api changes by any developer.

**Comment by tomharvey** [comment]
Yeah. I was unsure on how to best handle this. Is your suggestion here to then share the test account api keys?

Thanks for the PRs

**Comment by ordinathorreur** [comment]
Probably best not to add test account api keys, as you've rightly not done. Each developer can get their own.
I would first try to see if it's possible to record one or two api calls in a setup function to get the (remote) object into the state required to sufficiently test the result of the actual api call being tested.
I didn't have the time to look at the tests that were failing, which is why I only raised an issue, but perhaps traditional api response mocking, instead of recording actual ones, could be used for more problematic test setups. Webmock is already a project requirement, so api responses could be mocked with that.

**Comment by ordinathorreur** [comment]
I can take a look at adding another PR over the next couple of days, but something like the following seems to solve the issue.

```
context "finding an order" do

    before :each do
      VCR.use_cassette('order/finding_an_order--setup') do
        @order = Pwinty::Order.create(
          recipientName: "FirstName LastName",
          countryCode: "US",
          preferredShippingMethod: "Budget"
        )
      end
    end

    it "can get an order" do
	  	VCR.use_cassette('order/finding_an_order--get') do
        order = Pwinty::Order.find(@order.id)
	  	 	expect(order).to be_kind_of(Pwinty::Order)
	  	 	expect(order.id).to eq(@order.id)
	  	 	expect(order.recipientName).to eq('FirstName LastName')
		  	expect(order.countryCode).to eq('US')
		  	expect(order.preferredShippingMethod).to eq('Budget')
      end
	  end
	end
```

**Comment by tomharvey** [comment]
That would be awesome, thanks!

**Comment by tomharvey** [comment]
Resolved by https://github.com/tomharvey/pwinty3-rb/pull/15
